version: "2"

linters:
  enable:
    - bodyclose
    - goprintffuncname
    - misspell
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - whitespace
    - govet
    - gofmt
    - goimports
    - revive
  disable:
    - errcheck  # Too noisy for initial development
    - ineffassign
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/KyleKing/gh-sweep

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - .phases
    - docs
